### ISSUE TITLE
"Complete secured FAQ" option v2.9 - can't unset

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1143] opened 2016-05-14 12:45 UTC
Once set, it seems you are unable to `unset` the option on the admin page.
No error is presented, however the option remains checked and the system remains secured access only.

**Comment by mtompkins** [comment] 2016-05-14 12:58
FYI: Manually setting `enableLoginOnly` to false does reset access as expected.

**Comment by mtompkins** [comment] 2016-05-14 13:04
Well, while I'm able to login and the correct frontpage shows, now all FAQs are no longer shown. Seems this borks the entire solution. Putting the setting back to false does not bring the FAQs back.

This may be a rather significant problem if unchecking that box causes such a break.

**Comment by mtompkins** [comment] 2016-05-14 13:06
Little more - FAQs are still accessible on the Admin side. After resetting a single record to a category they all populate on the front end `whew`

**Comment by mtompkins** [comment] 2016-05-14 13:08
Last bit here - I'm downgrading as there seems to be some large issue in play here.

After that category reset. Logging out then back in, all records are gone again. Once you go to the admin side and update a record - they all populate again.

Good luck.

**Comment by thorsten** [comment] 2016-05-14 18:28
Checking/Unchecking "complete secured FAQ" works for me without any problems.

**Comment by thorsten** [comment] 2016-05-14 18:30
Do you have the database of your "borked" version? If yes, please send it to me, so I can test it.

**Comment by RWarnecke** [comment] 2016-05-14 18:34
I have no problems with the complete secured FAQ option. I can enable and disable this option **without** any problems.

**Comment by thorsten** [comment] 2016-05-14 19:38
As I cannot reproduce it, I'll close this issue

**Closed by thorsten** 2016-05-14 19:38 UTC
Labels: Bug
