### ISSUE TITLE
Problem with anchor & table of contents

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1733] opened 2020-04-17 14:37 UTC
**Describe the bug**
When i use anchor or table of contents in FAQ, in the display page, URL is not good and if i click on we return to phpmyfaq homepage.

Example :
URL anchor : http://localhost/#mcetoc_1e648s41r0 => Return to home page
The correct URL would be: http://localhost/?sid=12182&lang=fr&action=faq&cat=1&id=24&artlang=fr#mcetoc_1e648s41r0
(example without url rewriting)

PS : Tiny editor is different between frontend and backend (no table of content in frontend)

**To Reproduce**
1. Create a FAQ with anchor or table of contents
2. Go to FAQ frontend and show article
3. Click on anchor link

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Chrome
Version : 80

**Comment by thorsten** [comment] 2020-04-17 17:05
Duplicate of #1467

**Closed by thorsten** 2020-04-17 17:05 UTC
