### ISSUE TITLE
Session timeout despite "remember me" selected by login

### ISSUE THREAD

**Issue by robin-masters** [thorsten/phpMyFAQ#1024] opened 2015-05-19 07:09 UTC
Greetings,

i mentioned the problem already:
https://github.com/thorsten/phpMyFAQ/issues/948

My current version is PHPmyFAQ Version: 2.8.22

Despite i allready logged in (with password remember me) and i can use the frontend, following is not possible after uncertain time.

- quick search \ schnellsuche doesnt work after a while but the normal search works..
- search for internal links
- sometimes it`s necessary to Login again to create a new FAQ but the full secured frontend works without a new login
- Upload from new files (attachments or Pictures) requires to login again. (but you have to logout from phpmyfaq and Login again)

The cookie seems not work for the admin panel \ Editor correctly.

My constants.php (24h timeout)
[code]
/**
 * Timeout for the admin section, in minutes
 *
 * @var integer
 */
define('PMF_AUTH_TIMEOUT', 1440);

// Misc parameters
define('PMF_LANGUAGE_EXPIRED_TIME', 28800); // 30 minutes
define('PMF_SESSION_EXPIRED_TIME', 28800); // 30 minutes
define('PMF_REMEMBERME_EXPIRED_TIME', 1209600); // 2 weeks

[/code]

My php-settings concerning Sessions.
http://2moons.zapto.org/phpinfo-session.jpg

I use Internet Explorer 11 and have emptied the complete cache and so on, but same behavior.

**Comment by thorsten** [comment] 2015-06-03 18:52
phpMyFAQ didn't logged me out on my test system for the last 4 days. I deleted all cookies before I started the test. I even rebooted my Mac several times. I even could not reproduce your issues.
Note: I did the tests with latest Firefox, Chrome and Safari on OS X Yosemite.

**Comment by robin-masters** [comment] 2015-06-04 08:31
Greetings,

and you set the same values in the constants.php?
And it`s possible to create and edit FAQ`s, upload Pictures and set links to other FAQ`s without a relogin? Because the configuration for admin-panel let expire your login after 24h...

My colleague used the Firefox and there it works also not correctly - but he leastwise logged in in the Admin Panel for 24h but he also can`t set internal links or upload Pictures after awhile - he has first to relogin to the admin Panel..

With the IE 11 iam logged out after 1h...or 2h i cant say exactly but not after 24h. And when the Admin Panel ist open i cant set phpmyfaq links or upload Pictures but can navigate through the admin section... really strange behavior. :-(

With the front end are no problems.

If there a chance to test it with Windows7?

**Comment by arcaine2** [comment] 2015-06-04 09:29
He isn't the only one with that problem. I have the same issue on at least 3 computers (with Windows 7 and XP), using Firefox and new, blink based Opera. In my case it works that way:
1. I log in (with remember me set), everything's working.
2. After over 1 hour of inactivity i might refresh refresh the page or try to add new entry. The online counter changes to: "| 0 Guests and 1 Registered" instead of "1 user online | 0 Guests and 1 Registered".
3. At this point, when i try to add new entry i can fill all the data and the moment i click submit i get red "you're not authorized".
4. I can stil browse, search and read added entries. When i try to enter admin panel it allows me to do so but "session expires" counter says loading all the time.

To make everything working properly again i have to manually log out and then log back in.

I tried to change PMF_AUTH_TIMEOUT and PMF_SESSION_EXPIRED_TIME higher up. Did not fix the issue. PMF_SESSION_EXPIRED_TIME makes the pmf_sid cookie to last more than 60 minutes but the problem still remains and i can't add new faq entry without logging out and logging back in again.

1. Just logged in, everything's working properly, remember me checked, cookie set to 1 hour.
![faq1](https://cloud.githubusercontent.com/assets/12737015/7981042/90ecac56-0aac-11e5-9555-972239e1496a.png)
![faq1_pmf_sid](https://cloud.githubusercontent.com/assets/12737015/7981046/92425e0c-0aac-11e5-9989-396d11eda50b.png)
2. It was late at night, couldn't wait much longer so left the PC. That's what i see in the morning. pmf_sid cookie refreshed but i'm limited now, the online user counter is broken, not authorized anymore etc.
![faq2](https://cloud.githubusercontent.com/assets/12737015/7981050/967fc4d2-0aac-11e5-83a6-cb0902848135.png)
![faq2_pmf_sid](https://cloud.githubusercontent.com/assets/12737015/7981052/979fd672-0aac-11e5-92b2-5cbb83371d0b.png)
![faq3_not_authorized](https://cloud.githubusercontent.com/assets/12737015/7981069/bbfca1c6-0aac-11e5-9b67-32a2c6df4d2a.png)

**Comment by thorsten** [comment] 2015-06-04 09:38
Thanks for the hints, I'll try to reproduce it again with your additional notes!

**Comment by thorsten** [comment] 2015-06-04 10:13
Please check the two commits if that helps.

**Comment by robin-masters** [comment] 2015-06-04 11:39
Okay i currently use the new CurrentUser.php and i will inform you what happens...

**Comment by arcaine2** [comment] 2015-06-04 15:16
I need to check how it'll behave overnight but so far, after leaving the website inactive for over 3 hours everything seems to be working fine. Online counter is correct, admin session is refreshing properly, no information about not being authorized.

**Comment by robin-masters** [comment] 2015-06-04 15:33
Same like arcaine2 looks good at the moment (for 4 hours) - will see tomorrow morning if it still works.

**Comment by thorsten** [comment] 2015-06-04 18:33
Ack, I can reproduce the deletion error.

**Comment by thorsten** [comment] 2015-06-04 18:44
This commit fixes the deletion issue, it caused a lot of other regressions as well.

**Comment by robin-masters** [comment] 2015-06-05 07:16
Hmm get back on my PC today and push the F5 to refresh and he want`s to relogin...
Github for example stayed logged in. ;-) (IE11 Windows7)

My colleague with (IE11 Windows7) can navigate but he cant upload attachements, seems also he`s not correct logged in. After relogin it works. 
Have the same issue like him after logged in for 5 min. I have to relogin then. But i can navigate through the Front End and Admin Panel.

My other colleague with (Firefox Windows 8.1) create a new faq uploaded an attachment delete it and clicks then on the back button (to accept the message). Following he landed on a faq where stands in the Editor Text "access denied" and two other attachments it is an existing FAQ.
Very Strange. It`s seems he want get back to an FAQ what dont exist (is this an Cookie Problem or a new Problem?)

Tried this with IE11 and same Problem.

Should i use the standard constants.php for testing?

**Comment by thorsten** [comment] 2015-06-05 07:27
Yes, we should try that. Did a lot of testing today as well and it works quite smooth for me.

**Comment by robin-masters** [comment] 2015-06-05 08:44
Okay, i check the CurrentUser.php; session.keepalive.php again and it is exactly a copy of yours.
Additionally i use now the standard constants.php.

Will see what happens.

The other "bug" seems bear no relationship with the current issue.

Deleting an attachment in a new FAQ (not saved before), after it phpmyfaq Show me a page who it write that the attachment was successfully deleted. I have to klick on "back" now and then it brings me to following.

[img]http://2moons.zapto.org/images/phpmyfaq_error.jpg[/img]

**Comment by robin-masters** [comment] 2015-06-05 08:58
Okay Problem still exists.
Logged in with remember me and an navigate trough the menus but attachment Upload dont work an 
quicksearch and linking to other phpmyfaq faqs look at this:
I use https and i dont use the .htaccess - is this a problem?

<img src="http://2moons.zapto.org/images/phpmyfaq_error2.jpg">

**Comment by robin-masters** [comment] 2015-06-05 09:46
Okay the Bug "Deleting an attachment in a new FAQ (not saved before), after it phpmyfaq Show me a page who it write that the attachment was successfully deleted. I have to klick on "back" now and then it brings me to following." leads to the bug "Access denied quick search and Attachment upload".

Before i delete a Attachment all works fine.

**Comment by thorsten** [comment] 2015-06-05 10:00
Okay, I forgot ot checks... should be all fixed now. Thanks a lot for testing! Really appreciate that!

**Comment by arcaine2** [comment] 2015-06-05 12:30
One more thing i also had since yesterday (after applying the fix to solve deleting issue). I double checked it today with the changes made through the night.

When i log in and leave website inactive on the main site for over 60 minutes, the moment i click on "Administration" button i'm kicked out and asked to log back in. That's with PMF_AUTH_TIMEOUT set to 600 (once i log in into admin panel there's a countdown from 10 hours, like it should).

**Comment by robin-masters** [comment] 2015-06-05 14:22
Okay i have implemented  the new files - Problem -->"Deleting an attachment in a new FAQ (not saved before), after it phpmyfaq Show me a page who it write that the attachment was successfully deleted. I have to klick on "back" now and then it brings me to following."<-- is not fixed. "Access denied" and i have to relogin.

Will see if i leastwise stay longer logged in now.

**Comment by robin-masters** [comment] 2015-06-05 15:46
Okay i still logged in over a hour. This Looks good at the Moment. Quick search and so on works.
(will continuing testing next week)

But like i said when i delete an attachment in an unsaved faq and go back to this after confirm the deletion. Iam logged off....(cant use Ajax\Editor i thing)

At the moment a nice Weekend for all...

**Comment by thorsten** [comment] 2015-06-07 13:36
I checked your issue and it's working for me.

**Comment by robin-masters** [comment] 2015-06-08 09:15
Okay iam logged in for more then two days, but access issue still exists.
After 1 hour:
<img src="http://2moons.zapto.org/images/phpmyfaq_error2.jpg">
Quicksearch, Upload only works after relogin.

I can navigate and so on but Ajax Scripts seems doesnt work.
remember_since is set in the mysql db.

I have no Idea what`s the problem... :-(

**Comment by robin-masters** [comment] 2015-06-08 11:48
Something more about my installation... i use group rights.
A global group where alle users in, have only access to the FAQ`s and can create faq`s and so on.
But i thing that`s not the problem...

I will continue testing...

**Comment by robin-masters** [comment] 2015-06-08 15:02
Okay i was able to precise the time when the ajax scripts dont work... after 30min.

**Comment by robin-masters** [comment] 2015-06-09 08:07
hmm the quicksearch in the frontend works now - more then 20h and i`am correctly logged in for this time. I can edit and create FAQ`s as well. This looks good.

But "internal phpMyFAQ Links" doesnt work and "add an attachment".
This two things dont work after something around 30 minutes.

Eventually i should first install your new version 2.8.23... i could make a mistake implementing the new files but i dont think so.

**Comment by thorsten** [comment] 2015-06-09 08:08
Okay, please check if this file is correct for you:

https://github.com/thorsten/phpMyFAQ/blob/3e420fced8a420ec65f0f103495043761d916136/phpmyfaq/admin/editor/plugins/phpmyfaq/dialog.php

**Comment by robin-masters** [comment] 2015-06-09 08:30
Okay iam testing it but seems the same dialog.php like the old one from here:
https://github.com/thorsten/phpMyFAQ/commit/3e420fced8a420ec65f0f103495043761d916136
I had allready implemented it but i`am testing now the new one.

**Comment by robin-masters** [comment] 2015-06-09 10:16
Hmm once more after 30 min. same issue .... "search for internal phpmyFAQ Links" and "Attachments" dont work... all other seems okay. Really strange... :-(

**Comment by thorsten** [comment] 2015-06-09 17:39
Both functions are working for me. @arcaine2 any results on your test?

**Comment by arcaine2** [comment] 2015-06-09 19:53
It's inconsisent for me. During the last tests i'm logged in fine after 1 hour or 2 hours, but once in a while it kicks me out when i try to access the admin panel. For example, it did it for me today at work. Webside was inactive for over 4 hours, i wanted to edit something and got back to login screen. Right now, at home it's been 2,5 hour and it still works just fine.

Either way, as long as i'm asked to log back in before the action after a bit on inactivity is acceptable for me. The initial problem when i was suddenly not authorized the moment i tried to add or edit some faq entry is gone.

**Comment by robin-masters** [comment] 2015-06-10 07:45
I have an idea - i changed the date format to "d.m.Y H:i" is this eventually the problem?
Otherwise i have only  customised the template and the language_de.php - but should not be a problem.

**Comment by thorsten** [comment] 2015-06-10 07:47
Nope, I have the same date format :-)

I think I'll release the 2.8.23 asap and if there's still an issue, we should create a new ticket. What do you think?

**Comment by arcaine2** [comment] 2015-06-10 08:19
I think it's about time. The main problem was fixed, there are some smaller issues left. 

I've changed PMF_SESSION_EXPIRED_TIME to last for 10h instead of 1 and will see if i'll be still logged in at the end of the day.

**Comment by robin-masters** [comment] 2015-06-10 08:51
I think also i should try first your new release and will see what happens.
My only problems now are internal PHPmyFAQ Links and attachments. 
Quick Search on front panel works, i correctly stayed logged in in admin panel... its all fine.
So many bugs are fixed.

**Comment by robin-masters** [comment] 2015-06-10 13:18
@thorsten you tested it with mac and safari? I can get a macbook air to test my installation.
If the issus no exists we know it is an internet explorer or windows problem.

**Comment by thorsten** [comment] 2015-06-10 13:19
Yes, I'm working on a Mac and have Windows 7 as VM, but hadn't had the time to test it on my Win7 VM yet.

**Comment by robin-masters** [comment] 2015-06-10 16:57
Okay same issue with mac and safari ... not a windows/internet explorer problem.

Will make a test with a new phpmyfaq installation tomorrow.

Do you use an installation of phpmyfaq on Apache with linux(Ubuntu/Debian) or nginx?

**Comment by robin-masters** [comment] 2015-06-11 11:13
Okay Testinstallation is running with same configuration like my current installation.
First i try it without https... then i will use the standard template and so on back to the roots will see when it works..

**Comment by robin-masters** [comment] 2015-06-12 12:31
okay https and my template, constants.php are not the problem.
It`s all default now and same issue.. will trying to make a new installation evt. it`s something with our network.. proxy, firewall

**Comment by thorsten** [comment] 2015-06-13 09:31
Oky, thanks for the feedback, will close this issue and release 2.8.23. Finally! If you still found an issue, please open a new one for 2.8.24. Thanks a lot @robin-masters and @arcaine2 !

**Closed by thorsten** 2015-06-13 09:31 UTC
Labels: Bug

**Comment by robin-masters** [comment] 2015-06-16 07:16
Hey Thorsten, the update works for me now. Seems i have made an error somewhere (copying the new files)

Great work! Thanks!

**Comment by thorsten** [comment] 2015-06-16 07:17
Awesome! Thanks!
