### ISSUE TITLE
phpMyFAQ does not accept correct password

### ISSUE THREAD

**Issue by s1h4d0w** [thorsten/phpMyFAQ#1409] opened 2018-02-02 12:15 UTC
I have just installed version 2.9.9 of phpMyFAQ on my server with PHP 5.6.30 and MySQL 5.5.58 but I can't log in.

I created a user during the setup and tried logging in after. I was sure to enter my password correctly but it kept saying it was incorrect. I then requested a new password, received the email, but that new password is also incorrect according to the website.

I later found out that the documentation said to log in with username "admin" the first time, but that doesn't work either, not with my chosen password or the new password I got from the reset email. It says the username is not found (only for admin, my normal username got blocked for trying too many times).

Is this a know bug? How do I get around this, I'd like to start setting up the website and adding information.

## Edit
I decided to simply reinstall everything from scratch, and I was now able to log in to the admin section using my own username and chosen password. Logging in as username "admin" like the documentation says did not work. 

I still have no idea how I was able to log in suddenly, but there is definitely a bug somewhere, I should have been able to log in with my username and the password from the reset email.

**Comment by thorsten** [comment] 2018-02-04 11:59
As noted in our forums, I couldn't reproduce this issue.

**Comment by Adipsys** [comment] 2018-02-15 14:32
Hello,

I'm also having weird behaviour with passwords in 2.9.9. 
Some clients reported to me that their password wasn't working anymore. They used "forgot password" and received a new pass which wasn't working either.
I had to reset from the admin and for some it worked without new issue and for some other the pass was still not working on their side but working on mine... pretty hard to understand :(

I'm trying to reproduce the issue but unfortunately without success as it seems to appear randomly.
I don't know where to investigate to give you more precise elements.

**Comment by EldoBam** [comment] 2018-02-15 14:37
maybe it's an encoding thing?

**Comment by nighknight** [comment] 2018-08-24 08:43
It may be the brute-force protection. It already blocks the access after one wrong password. So if you (by accident) mistype your password, you are blocked afterwards. It probably stays like this even if you request a new password.

I would recommend to check if the corresponding user is blocked in the DB.

In my own installation, I reduced to blocking time significantly. This should slow down scripts, but keep users happy who just mistyped their password.

See as well #1333.

**Comment by Adipsys** [comment] 2018-08-24 09:31
Yes I confirm it is related to that brute force check. I commented it for the moment as I already have (on my 2.9.9) the fixes made by Thorsten in #1333.
Here's how to reproduce it : 
- Log with a wrong password => in faquser table the account_status is active but the "success" is 0
- As long as this success value is 0, the user isn't able to log in with the right password or even after a reset.

I guess I could change the lockoutTime = 600 to a lower value but I'll wait for a fix.

As @nighknight suggested in #1333 the lock should be improved to something like after 5 wrong attempts.

Thanks :)

**Comment by thorsten** [comment] 2018-08-24 17:56
You have to wait 10 minutes currently.

**Comment by Adipsys** [comment] 2018-08-27 07:30
That's what I understood :) but it might be relevant also to set an attempt limit before the 10 min.

**Comment by nelsondcosta23** [comment] 2019-01-21 11:02
Hi guys, there is any news about this topic?!

Thanks

**Comment by nighknight** [comment] 2019-01-21 11:50
Yes, see #1525.

**Comment by thorsten** [comment] 2019-01-21 16:12
Closed as this is fixed in 3.0.0-alpha.4

**Closed** 2019-01-21 16:12 UTC
Labels: Needs feedback
