### ISSUE TITLE
Group rights change automatically

### ISSUE THREAD

**Issue by KL7000F** [thorsten/phpMyFAQ#2197] opened 2022-08-25 13:21 UTC
Hello,

Group rights change automatically, without the intervention of an admin.

In the category, access was only assigned to some user groups. After some time this will be set back to "Access for all groups". Only new FAQ were created. Otherwise no changes to the user groups, categories, etc.

![faq](https://user-images.githubusercontent.com/16374462/186676018-c5d92afd-2272-4c5b-bb55-619d91103839.png)

Version: 3.1.6

Addendum: The marked user groups are also incorrect.

Greez
KL7000F

**Comment by thorsten** [comment] 2022-09-03 15:03
I cannot reproduce this issue. Is it possible, that a second admin changed the value by accident?

**Comment by KL7000F** [comment] 2022-09-03 16:49
Actually impossible, since only I administrate. So far, however, the error has not occurred again. I'll keep an eye on it.

**Comment by thorsten** [comment] 2022-09-03 17:15
Okay, I'll close it for now.

**Closed by thorsten** 2022-09-03 17:15 UTC
Labels: Bug
