### ISSUE TITLE
(3.2 alpha) search + enter not working

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2378] opened 2023-03-15 09:05 UTC
Main branch as of 2023-0315

First setup and categories/faq setup.

Just some observations for you Thorsten about my first steps using 3.2 alpha.

0.) webservice v2.2 works for all the requests I made - so thanks for that. I used a 1 second delay between requests. Anything less seemed to overwhelm the container. Not an issue for me as I like drinking tea !
 
1.) I think the counts for the faq in the category feature we discussed in a previous issue (#2292) don't seem to be accurate. they are all at zero, yet there is approximately 800 faq somewhere in the database.
![image](https://user-images.githubusercontent.com/121568455/225259635-ed999957-9d62-4240-b712-0317eeb148a5.png)

2.) [ see - #2293 ] Enter search term + enter key in search bar doesn't start a search - nothing happens.

**Comment by thorsten** [comment] 2023-03-16 20:52
Duplicate of #2377

**Comment by thorsten** [comment] 2023-03-16 21:05
sorry, oversaw point 2

**Comment by mark-Wh** [comment] 2023-03-20 07:57
ok - point 1.) a duplicate. Fine.
Willl get latest this week and try out point 2.), along with the other things I need to check.
Will reply back in next couple of days.

**Closed** 2023-03-21 19:58 UTC
Labels: Bug, Needs feedback

**Comment by mark-Wh** [comment] 2023-04-04 08:13
Tried as part of #2377
Pressing enter key uses search criteria as entered in the search bar.

When typing search terms there is the helpful list view which appears but actually pressing the enter key uses the search terms rather than the first list item in the helpful list view.

This is a great enhancement to "old people" like me who use keyboard.

It works great.
