### ISSUE TITLE
FAQ Search Generates SQL Exception

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2424] opened 2023-04-10 17:08 UTC
Under Administration>Content>Search for FAQs, entering anything/nothing in the search box and hitting search generates the below error.

```
phpMyFAQ Fatal error
Uncaught exception: 'mysqli_sql_exception'

Message: 'Can't find FULLTEXT index matching the column list'

Stack trace:

#0 /var/www/html/src/phpMyFAQ/Database/Mysqli.php(311): mysqli->query()
#1 /var/www/html/src/phpMyFAQ/Search/Database/Mysqli.php(95): phpMyFAQ\Database\Mysqli->query()
#2 /var/www/html/admin/record.show.php(262): phpMyFAQ\Search\Database\Mysqli->search()
#3 /var/www/html/admin/index.php(356): require('...')
#4 {main}
Thrown in '/var/www/html/src/phpMyFAQ/Database/Mysqli.php' on line 311
```

**Comment by thorsten** [comment] 2023-04-11 05:19
Does your faqdata table looks like this?
<img width="976" alt="Bildschirmfoto 2023-04-11 um 07 18 43" src="https://user-images.githubusercontent.com/45284/231063190-a6077604-6215-467e-8e1f-ae0973960257.png">

**Comment by wwalker0307** [comment] 2023-04-11 06:57
No, all tables are showing InnoDB.

![image](https://user-images.githubusercontent.com/36755138/231080734-1bdd7d33-f3d3-4228-a2c5-ec4883e33021.png)

**Comment by thorsten** [comment] 2023-04-11 07:14
Okay, this is the query this is executed during the search:

`SELECT faqdata.id AS id, faqdata.lang AS lang, faqdata.solution_id AS solution_id, faqcategoryrelations.category_id AS category_id, faqdata.sticky AS sticky, faqdata.active AS active, faqdata.thema AS thema, faqdata.content AS content, faqdata.updated AS updated FROM faqdata LEFT JOIN faqcategoryrelations ON faqdata.id = faqcategoryrelations.record_id AND faqdata.lang = faqcategoryrelations.record_lang WHERE MATCH (faqdata.thema, faqdata.content, faqdata.keywords) AGAINST ('test' IN BOOLEAN MODE)`

**Comment by wwalker0307** [comment] 2023-04-11 13:31
I'm not super familiar with using MATCH and AGAINST, but it looks like you are missing the operator for AGAINST? I think it would go `AGAINST (+'test' IN BOOLEAN MODE)`.

**Comment by wwalker0307** [comment] 2023-04-11 13:38
Interestingly, when I run the query with and without the `+` in MySQL directly, they both return the same values and work.

**Comment by thorsten** [comment] 2023-04-11 14:16
`+` is the AND search: https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html

**Comment by thorsten** [comment] 2023-04-14 09:33
You still get the error when using FAQs in the admin backend, right?

**Comment by wwalker0307** [comment] 2023-04-15 06:30
Unfortunately, I did a dumb thing and lost my entire virtual environment.  I just got phpMyFAQ Alpha.2 up and running from scratch and this is not an issue, so it appears to have been an issue with upgraded databases...unfortunately I have no way of helping with this anymore :(

**Comment by thorsten** [comment] 2023-04-15 07:31
Okay, thanks for the feedback. As I can't reproduce it, I close the issue.

**Closed** 2023-04-21 13:33 UTC
Labels: Bug
