### ISSUE TITLE
Aligning use of classes on start page

### ISSUE THREAD

**Issue by werkstrom** [thorsten/phpMyFAQ#1592] opened 2019-09-29 19:36 UTC
On `startpage.html` different classes are used for startPageCategories (first "row div" on the page) and the boxes below (the second "row div" on the page) and the margins within them are set differently resulting in uneven distances between columns in these two divs (slightly wider margin on the top row)

Adjusting `styles.css` and the `card-deck` class as per below appears to resolve the issue. This also adjusts to using rem (mainly) instead of px.

```
.card-deck {
  display: flex;
  flex-direction: column; }
  .card-deck .card {
    margin-bottom: 0.75rem; }
  @media (min-width: 576px) {
    .card-deck {
      flex-flow: row wrap;
      margin-right: -0.625rem;
      margin-left: -0.625rem; }
      .card-deck .card {
        display: flex;
        flex: 1 0 0%;
        flex-direction: column;
        margin-right: 0.625rem;
        margin-bottom: 0;
        margin-left: 0.625rem; } }
```

**Comment by thorsten** [comment] 2019-09-30 05:54
Please don't change something in the CSS files, please use the SCSS files.

**Comment by werkstrom** [comment] 2019-09-30 11:54
Are these classes present in the scss files? I cant find them there? I looked there first but then again, I'm not a (s)CSS-guru either 😉

**Comment by thorsten** [comment] 2019-10-01 06:09
These classes look like directly from Bootstrap.

**Comment by thorsten** [comment] 2019-12-24 14:33
I tried to understand this issue, can you explain it for me?

**Comment by werkstrom** [comment] 2020-01-02 08:34
Being on holiday I missed this, sorry. We did change the css locally just to test and I can probably supply screenshots that illustrate the issue. After the fix the layout looks as (I believe) it should.

**Comment by thorsten** [comment] 2020-01-02 08:36
Would be great!

**Comment by thorsten** [comment] 2020-01-03 07:52
@werkstrom would it be okay to move this issue to final release of phpMFAQ 3.0.0. I would release 3.0.0-RC today or tomorrow.

**Comment by thorsten** [comment] 2020-01-20 19:16
Any news on this one?

**Comment by werkstrom** [comment] 2020-01-21 11:32
Sorry, haven't checked or tested. Just back after the holidays and there is to much work. :-(

**Comment by thorsten** [comment] 2020-01-21 11:39
No worries, I would close it nevertheless. If the issue is still present, please open a new issue. Thank you very much!

**Closed by thorsten** 2020-01-21 11:39 UTC
Labels: Improvement
