### ISSUE TITLE
It should be possible to change password for a user if you have the "user rights" to change password on users

### ISSUE THREAD

**Issue by jesa43** [thorsten/phpMyFAQ#984] opened 2015-03-11 10:36 UTC
Its is impossible to change password for a user from the admin point of view. When you are using the PMF FAQ without emailing its not possible to change the password for users that forget their password.

**Comment by thorsten** [comment] 2015-03-11 11:29
Duplicate of #770, it's in the works for v2.9.0-alpha3

**Closed by thorsten** 2015-03-11 11:29 UTC
