### ISSUE TITLE
Sorted Categories

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1450] opened 2018-05-05 23:06 UTC
To implement a new option, that the categories are automatically sorted in the view of the fronted and backend.

**Comment by thorsten** [comment] 2018-05-06 11:00
hm, they are sorted the same way.

**Comment by RWarnecke** [comment] 2018-05-06 19:06
I mean sorted alphabetically. If I create a new sub category the position of the new category is at the end of the list.

**Comment by thorsten** [comment] 2018-05-07 05:54
But you can sort the categories already manually. :)

**Comment by RWarnecke** [comment] 2018-05-07 16:45
Yes, I can sorted manually, but If you have for example 20 sub categories and you add a new one. phpMyFAQ add the new sub category at the end of the other 20 sub categories and if you want to sort it at index 2 it was a lot of click work. I think a option to sort it manually or alphabetically was a nice feature. Or you change the manually sorting to two options. The first is switch with the other selected sub category or you can edit the target index for your new sub category.

**Comment by thorsten** [comment] 2018-05-07 16:52
Duplicate of #1306

**Closed by thorsten** 2018-05-07 16:52 UTC
Labels: Needs feedback

**Comment by RWarnecke** [comment] 2018-05-07 16:57
It was not a duplicate. 1306 is only the view in the edit faqs section. This issue is for to add a new category and it was sorted automatically or manually.
