### ISSUE TITLE
Restricted access FAQ shows "This entry is in revision and can not be displayed. " instead of smth like "Access denied"

### ISSUE THREAD

**Issue by EmilFurniga** [thorsten/phpMyFAQ#696] opened 2013-06-22 09:57 UTC
When trying to access a FAQ which is only public for a certain group, the displayed message is "This entry is in revision and can not be displayed."

I think it should show smth like "Access denied" and then display a login form for the user.

**Comment by thorsten** [comment] 2017-12-10 08:43
Duplicate of #695

**Closed by thorsten** 2017-12-10 08:43 UTC
