### ISSUE TITLE
Cannot display the FAQ question

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#1975] opened 2021-08-02 13:26 UTC
Dear All,

Since a few days it has been impossible to display an entered question from the phpmyfaq site in user mode. (The question is accessible via the admin console, but also when the function view "view FAQ" is called, the error occurs.

I've run the site in debug mode and get the following error when I try to open a question:

Fatal error: Uncaught TypeError: phpMyFAQ\Search\Database\Mysqli::search(): Return value must be of type mysqli_result, bool returned in /mnt/web109/e2/67/54355767/htdocs/mijn_faq/src/phpMyFAQ/Search/Database/Mysqli.php:121 Stack trace: #0 /mnt/web109/e2/67/54355767/htdocs/mijn_faq/src/phpMyFAQ/Relation.php(88): phpMyFAQ\Search\Database\Mysqli->search() #1 /mnt/web109/e2/67/54355767/htdocs/mijn_faq/faq.php(177): phpMyFAQ\Relation->getAllRelatedByQuestion() #2 /mnt/web109/e2/67/54355767/htdocs/mijn_faq/index.php(710): require('...') #3 {main} thrown in /mnt/web109/e2/67/54355767/htdocs/mijn_faq/src/phpMyFAQ/Search/Database/Mysqli.php on line 121

When de site is not in debug mode I get an error 500

- phpMyFAQ version 3.0.9
- PHP version 7.3
- Database mysql
- Elasticsearch yes/no no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] chrome edge, firefox
- Version [e.g. 22] latest browser versions

**Comment by ton-helmerhorst** [comment] 2021-08-04 20:14
Many thanks for your feedback!!

I change the file with the suggested modifications, but I get now the following error:

Fatal error: Uncaught Exception phpMyFAQ\Exception with message Error while fetching result: Can't find FULLTEXT index matching the column list in /mnt/web109/e2/67/54355767/htdocs/mijn_faq/src/phpMyFAQ/Database/Mysqli.php: 142 Stack trace: #0 /mnt/web109/e2/67/54355767/htdocs/mijn_faq/src/phpMyFAQ/Relation.php(90): phpMyFAQ\Database\Mysqli->fetchAll() #1 /mnt/web109/e2/67/54355767/htdocs/mijn_faq/faq.php(177): phpMyFAQ\Relation->getAllRelatedByQuestion() #2 /mnt/web109/e2/67/54355767/htdocs/mijn_faq/index.php(710): require('...') #3 {main} thrown in /mnt/web109/e2/67/54355767/htdocs/mijn_faq/src/phpMyFAQ/Database/Mysqli.php on line 142

**Comment by thorsten** [comment] 2021-08-05 05:40
Ah, thanks. Why is the FULLTEXT index missing? Is this a new installation? What database version do you use?

**Comment by ton-helmerhorst** [comment] 2021-08-05 07:11
Hi,

It's an existing installation version 3.0.9
MySQL version 5.7
PHP version 7.3

the problem occurred for the first time after adding a question. After this I got an error 500 error.

I made a backup of my database, deleted the current one and put the backup back to check if the issue came from the database. So the database has been restored with a backup.

**Comment by thorsten** [comment] 2021-08-07 14:51
Looks like the FULLTEXT index got lost. Do you need the Query to fix it?

**Comment by ton-helmerhorst** [comment] 2021-08-07 15:58
Hi,

That would be great if you could offer me a query to solve this!!!

Many thanks for this.

Greeting,

Ton

**Comment by ton-helmerhorst** [comment] 2021-08-11 03:37
Hi Thorsten,

I noticed that the problem occurs when an empty category is removed from the admin portal. The problem does not occur immediately, but after a few hours. I've put the site in debug mode, but then I don't get any more information than the previously presented error message.
If there is a possibility to check the performed actions in a log file, please let me know and I will offer it

**Comment by ton-helmerhorst** [comment] 2021-08-11 17:20
Dear Thorsten,

I looked further into the problem today and see that the Engine has changed from MyISAM to InnoDB in the table _faqdata
After changing the engine in the database, the data is accessible, but the cause of this problem is unknown to me.

**Comment by thorsten** [comment] 2021-08-14 10:20
ah, FULLTEXT search only works with MyISAM, not InnoDB

**Comment by ton-helmerhorst** [comment] 2021-08-14 12:34
Thanks Thorsten,

Is there a reason ( script ) why the engine is changing from MyISAM to InnoDB?  I have to change on daily base the engine setting to MyISAM. I have no idea why it's changing to InnoDB

**Comment by thorsten** [comment] 2021-08-14 12:36
That's a good question but I don't have an answer. The change is not coming from phpMyFAQ as we're using MyISAM:

https://github.com/thorsten/phpMyFAQ/blob/3.0/phpmyfaq/src/phpMyFAQ/Instance/Database/Mysqli.php#L151

**Comment by thorsten** [comment] 2021-08-22 17:09
I'll close this issue as it's not a bug in phpMyFAQ.

**Closed by thorsten** 2021-08-22 17:09 UTC
Labels: Bug
