### ISSUE TITLE
phpmyfaq web container keeps restarting

### ISSUE THREAD

**Issue by mulgurul** [thorsten/phpMyFAQ#1575] opened 2019-08-14 11:01 UTC
When using latest docker image, then the web server container just keeps restarting.

The log says:

`2019-08-14T10:54:30.595891790Z Enabling module rewrite.
2019-08-14T10:54:30.602013050Z Enabling module headers.
2019-08-14T10:54:30.606115554Z To activate the new configuration, you need to run:
2019-08-14T10:54:30.606134784Z   service apache2 restart
2019-08-14T10:54:30.608142401Z sed: can't read .htaccess: No such file or directory
2019-08-14T10:54:31.966645724Z Module rewrite already enabled
2019-08-14T10:54:31.966672414Z Module headers already enabled
2019-08-14T10:54:31.968888674Z sed: can't read .htaccess: No such file or directory
2019-08-14T10:54:33.160946527Z Module rewrite already enabled
2019-08-14T10:54:33.160980167Z Module headers already enabled
2019-08-14T10:54:33.163043963Z sed: can't read .htaccess: No such file or directory
`

Here's the compose stuff I have used:

`db_phpmyfaq:
    image: mariadb:10.2.14
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=iop
      - MYSQL_DATABASE=phpmyfaq
      - MYSQL_USER=phpmyfaq
      - MYSQL_PASSWORD=phpmyfaq
    volumes:
      - "/docker-data/phpmyfaq/mariadb:/var/lib/mysql"
  phpmyfaq:
    image: phpmyfaq/phpmyfaq:latest
    #build: ./phpmyfaq
      #context: .
      #dockerfile: ./phpmyfaq/Dockerfile
    restart: unless-stopped
    #stdin_open: true
    environment:
      - PMF_DB_HOST=db
      - PMF_DB_NAME=phpmyfaq
      - PMF_DB_USER=phpmyfaq
      - PMF_DB_PASS=phpmyfaq
      - PMF_DISABLE_HTACCESS=""
      - PMF_TIMEZONE="Europe/Berlin"
      - PMF_ENABLE_UPLOADS="On"
      - PMF_MEMORY_LIMIT="64M"
      - PHP_LOG_ERRORS="On"
      - PHP_ERROR_REPORTING="E_ALL" # Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
      - PHP_POST_MAX_SIZE="64M"
      - PHP_UPLOAD_MAX_FILESIZE="64M"
      #- DISABLE_HTACCESS="x"
      - VIRTUAL_HOST=phpmyfaq.ngt.dbb.dk
      #VIRTUAL_PORT: 9000
    
    links:
      - db_phpmyfaq:db
      - elasticsearch__phpmyfaq
    ports:
      - "8080:80"
    volumes:
      - "/docker-data/phpmyfaq/attachments:/var/www/html/attachments"
      - "/docker-data/phpmyfaq/data:/var/www/html/data"
      - "/docker-data/phpmyfaq/images:/var/www/html/images"
      - "/docker-data/phpmyfaq/config:/var/www/html/config"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    stdin_open: true
    links:
      - db_phpmyfaq:db
    environment:
      - VIRTUAL_HOST=phpmyfaq.ngt.dbb.dk
    ports:
      - "8000:80"
    volumes:
      - ./volumes/sessions:/sessions
  elasticsearch__phpmyfaq:
    image: elasticsearch:2.4.6
    restart: always
    environment:
      - cluster.name=phpmyfaq-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/docker-data/phpmyfaq/esdata:/usr/share/elasticsearch/data"
`

Seems like there's something wrong with the entrypoint script in relation to the folder structure or similar.
Kind of showstopper, so hope you can provide a fix or workaround...

Best regards, Peter

**Comment by thorsten** [comment] 2019-08-14 11:20
For which version did you tried it?

**Comment by mulgurul** [comment] 2019-08-14 11:52
Well I used :latest in image settings, so this would probably be latest stable? 2.9.13
I'm trying with 3.0 (beta) in this moment to see if it makes a difference.

Best regards

**Comment by mulgurul** [comment] 2019-08-14 11:55
I can confirm that if i use 3.0 then the container does not restart and I get the setup page stating version 3.0.0-alpha.2 from the web server:-)

**Comment by mulgurul** [comment] 2019-08-14 11:55
So the problem seems to be with image: phpmyfaq/phpmyfaq:latest version

**Comment by thorsten** [comment] 2019-08-14 15:15
The 2.9 Docker files and Docker Compose files are just for development. I'll fix the issue with 3.0-beta3

**Comment by jorgeag68** [comment] 2019-11-05 16:52
Any news about when the beta3 will be available ? Thanks.

**Comment by thorsten** [comment] 2019-11-09 15:06
Please test https://github.com/thorsten/phpMyFAQ/packages/52013

**Comment by jorgeag68** [comment] 2019-11-12 12:05
I'm using the docker compose.
Can I test with a modified version of docker-compose to get the new version ?

https://github.com/phpMyFAQ/docker-hub/blob/3.0/docker-compose.yml

**Comment by thorsten** [comment] 2019-11-12 12:34
Yes, clone this repository and use Docker Compose

**Comment by jorgeag68** [comment] 2019-11-12 14:12
Ok. I've cloned "https://github.com/thorsten/phpMyFAQ.git" and started docker-compose.
Still got errors and the container does not start.
---
phpmyfaq_1       | Module headers already enabled
phpmyfaq_1       | sed: can't read .htaccess: No such file or directory
phpmyfaq_1       | Module rewrite already enabled
phpmyfaq_1       | Module headers already enabled
phpmyfaq_1       | sed: can't read .htaccess: No such file or directory
phpmyfaq_1       | Module rewrite already enabled
phpmyfaq_1       | Module headers already enabled
phpmyfaq_1       | sed: can't read .htaccess: No such file or directory

Also ElasticSearch is not starting:

elasticsearch    | [2019-11-12T14:07:40,372][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch    | [2019-11-12T14:07:40,406][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	... 6 more
elasticsearch    | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch    | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch    | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_161]
elasticsearch    | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_161]
elasticsearch    | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_161]
elasticsearch    | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	... 6 more
elasticsearch    | [2019-11-12T14:08:08,863][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch    | [2019-11-12T14:08:08,895][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	... 6 more
elasticsearch    | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch    | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch    | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_161]
elasticsearch    | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_161]
elasticsearch    | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_161]
elasticsearch    | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	... 6 more
elasticsearch    | [2019-11-12T14:09:03,057][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch    | [2019-11-12T14:09:03,099][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	... 6 more
elasticsearch    | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch    | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch    | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_161]
elasticsearch    | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_161]
elasticsearch    | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_161]
elasticsearch    | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch    | 	... 6 more

phpmyfaq_phpmyfaq_1 exited with code 2


Hope this helps.

**Comment by thorsten** [comment] 2019-11-12 17:01
Did you delete all containers before rebuilding?

**Comment by jorgeag68** [comment] 2019-11-13 09:37
Yes. Removed all containers , and removed all images. 
Cloned https://github.com/thorsten/phpMyFAQ.git.
# cd phpMyFAQ/
# docker-compose up

**Comment by lightszentip** [comment] 2019-11-24 19:15
@jorgeag68 can you show your result for 
docker ps
docker ps --all
?

**Comment by jorgeag68** [comment] 2019-11-27 17:54
Hello. Output of the commands:

root@phpmyfaq:~# docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                                  PORTS                  NAMES
dab737dc7b81        phpmyfaq_phpmyfaq                                     "/entrypoint apache2…"   7 minutes ago       Restarting (2) 41 seconds ago                                  phpmyfaq_phpmyfaq_1
d3afaf725411        phpmyadmin/phpmyadmin                                 "/docker-entrypoint.…"   7 minutes ago       Up 5 minutes                            0.0.0.0:8000->80/tcp   phpmyfaq_phpmyadmin_1
d17708e384e7        mariadb:10.2.14                                       "docker-entrypoint.s…"   7 minutes ago       Up 5 minutes                            3306/tcp               phpmyfaq_mariadb_1
83c7db0f1808        docker.elastic.co/elasticsearch/elasticsearch:5.6.9   "/bin/bash bin/es-do…"   7 minutes ago       Restarting (1) Less than a second ago                          elasticsearch
root@phpmyfaq:~# docker ps -a
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                          PORTS                  NAMES
dab737dc7b81        phpmyfaq_phpmyfaq                                     "/entrypoint apache2…"   7 minutes ago       Restarting (2) 42 seconds ago                          phpmyfaq_phpmyfaq_1
6cee2dff80fb        node:latest                                           "docker-entrypoint.s…"   7 minutes ago       Exited (0) 4 minutes ago                               phpmyfaq_yarn_1
d3afaf725411        phpmyadmin/phpmyadmin                                 "/docker-entrypoint.…"   7 minutes ago       Up 5 minutes                    0.0.0.0:8000->80/tcp   phpmyfaq_phpmyadmin_1
6dadd67a3c15        composer:latest                                       "/bin/sh /docker-ent…"   7 minutes ago       Exited (0) 5 minutes ago                               phpmyfaq_composer_1
d17708e384e7        mariadb:10.2.14                                       "docker-entrypoint.s…"   7 minutes ago       Up 5 minutes                    3306/tcp               phpmyfaq_mariadb_1
83c7db0f1808        docker.elastic.co/elasticsearch/elasticsearch:5.6.9   "/bin/bash bin/es-do…"   7 minutes ago       Restarting (1) 1 second ago                            elasticsearch

**Comment by thorsten** [comment] 2019-11-30 11:59
Should be fixed with https://github.com/phpMyFAQ/docker-hub/commit/31f0597160d83ffe8b148250fe9c9449ddb2d6f5

**Comment by jorgeag68** [comment] 2019-12-02 17:22
Hello,

Getting this error while running: docker build -t phpmyfaq .

yarn run v1.19.1
error @thorsten/phpmyfaq@3.0.0-RC: The engine "node" is incompatible with this module. Expected version "^11.0". Got "13.2.0"
error Commands cannot run with an incompatible environment.

I've tried to pass the --ignore-engines on the Dockerfile without success.

**Comment by thorsten** [comment] 2019-12-03 17:44
Please try this version: https://github.com/thorsten/phpMyFAQ/commit/8d0281993be95f0531031168de4d9f593966edac

**Comment by thorsten** [comment] 2019-12-24 14:33
-> no feedback -> fixed

**Closed by thorsten** 2019-12-24 14:33 UTC
Labels: Bug, Needs feedback
