### ISSUE TITLE
Table border not visible

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1439] opened 2018-03-29 15:17 UTC
Hi Thorsten,

I found a possible bug adding a border in a table.
I also tried to add a tag with Tools <> source code and save... but it does not work.
No table border reloading the page.
Thanks for your help

Cheers,

Paolo Caparrelli
GOLINE SA

**Comment by thorsten** [comment] 2018-03-30 14:59
Duplicate of #1438 -> closed

**Closed by thorsten** 2018-03-30 14:59 UTC
Labels: Bug
